name: Analyze with CodeGuru Reviewer

on: [push, pull_request]

permissions:
    id-token: write
    contents: write
    security-events: write 

jobs:
  build:
    name: Clone your repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Echo the different SHAs
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}    
      run: |
        echo "github.event.before ${{ github.event.before }}"
        echo "github.event.pull_request.base.sha ${{ github.event.pull_request.base.sha }}"
        echo $GITHUB_CONTEXT

