name: Analyze with CodeGuru Reviewer

on:
  push:
    branches: [ main, master, martinschaef-patch-1, martinschaef-patch-3 ]
  pull_request:
    branches: [ main, master, martinschaef-patch-1, martinschaef-patch-3 ]
    types: [opened, closed]
permissions:
    id-token: write
    contents: write    # This is required for actions/checkout@v1

jobs:
  build:
    name: Clone your repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build gradle package
      run: ./gradlew build -x test

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::727015569506:role/GitHubOidcRole
        aws-region: us-west-2

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: true
      with:          
        s3_bucket: ${{ secrets.BUCKET_NAME }}
        build_path: ./build/libs

    - name: Upload review result      
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
